### ISSUE TITLE
Update Finagle/Prometheus dependencies

### ISSUE THREAD

**Issue by diversit** [samstarling/finagle-prometheus#35]
Please update the dependencies to the latest Finagle version (19.2.0) and Prometheus Java client (0.6.0)

**Comment by samstarling** [comment]
Hi @diversit: apologies for not having replied to this sooner – things have been busy. If you'd like to make a pull request, then I can try and get this reviewed and released ASAP for you. Thanks!

**Comment by liamstewart** [comment]
I see that the finagle dependency has been updated to 19.3.0 in 828232ba946b5c9cda0698b6fd5b2890be18b49f. Is it possible to push a new release? Thanks!

**Comment by samstarling** [comment]
Hi @liamstewart – I just pushed it to [Bintray](https://bintray.com/samstarling/maven/finagle-prometheus), and it's syncing to Maven Central at the moment.

**Comment by liamstewart** [comment]
Awesome - thanks so much!
