### ISSUE TITLE
Write some "getting started" documentation

### ISSUE THREAD

**Issue by samstarling** [samstarling/finagle-prometheus#5]
To be friendly to new users and promote usage, it'd be good to have an example of how to get up and running with the library.

**Comment by olli-miettinen-arm** [comment]
This would be nice to have.

**Comment by samstarling** [comment]
Hey @olli-miettinen-arm – I just updated the README, and there's now also an `examples` directory. Would you mind taking a look and letting me know if it's useful?

**Comment by samstarling** [comment]
I just gave the README some love, and now it has a proper description of everything the library does. @spockz, you might also be interested in this.

**Comment by spockz** [comment]
Nice. :)

Maybe we should also address how to set the per host statsreceiver and which extension possibilities the PrometheusStatsReceiver has.

Do you want to do that in a separate issue?

**Comment by samstarling** [comment]
@spockz Good idea, I just raised a new issue for this!
