### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by vilva42** [samstarling/finagle-prometheus#50]
Thanks for the work. Do you have a grafana dashboard for the metrics?

**Comment by samstarling** [comment]
Hey @vilva42 – sorry for the slow reply. I don't have a Grafana dashboard for this, but I was originally hoping to include one. Sadly I don't have so much time for this project any more, but is there a particular query or bit of data you were struggling to get? I'd be happy to help out.

Alternatively, if you (or anyone else) has a Grafana dashboard that works for them, I'd be happy to include it in the repository – you can export them as JSON.

**Comment by vilva42** [comment]
Hi @samstarling, sorry we decided to use json_exporter instead of the library because of dependency conflicts. Our finagle version was too old for this.
