### ISSUE TITLE
Local File

### ISSUE THREAD

**Issue by deepakmohanakrishnan07** [samstarling/finagle-prometheus#6]
Any idea? Just followed the code snippets shown in example EchoServer. The below error occurred while starting the finagle server.

```[ERROR] Exception in thread "main" java.lang.ExceptionInInitializerError
[ERROR] 	at MyServer.main(MyServer.scala)
[ERROR] Caused by: java.io.FileNotFoundException: /Users/samuelstarling/Development/personal/finagle-prometheus/target/scala-2.11/scoverage-data/scoverage.measurements.1 (No such file or directory)
[ERROR] 	at java.io.FileOutputStream.open0(Native Method)
[ERROR] 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[ERROR] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[ERROR] 	at java.io.FileWriter.<init>(FileWriter.java:107)
[ERROR] 	at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:42)
[ERROR] 	at scoverage.Invoker$$anonfun$1.apply(Invoker.scala:42)
[ERROR] 	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:901)
[ERROR] 	at scoverage.Invoker$.invoked(Invoker.scala:42)
[ERROR] 	at com.samstarling.prometheusfinagle.mapper.FinagleToPrometheusMapper.metricFamilySamples(FinagleToPrometheusMapper.scala:15)```

**Comment by furahm01** [comment]
@deepakmohanakrishnan1984 how you make it work, because I am adding the pom dependency but it says as follows:

Dependency com.samstarling:finagle-prometheus_2.11:0.0.1 not found

Br,

**Comment by samstarling** [comment]
Hey @deepakmohanakrishnan1984: sorry I never replied to this, I don't think Github ever notified me about it. It maybe looks like something related to the plugin that I use for generating code coverage. Can you paste the full exception? It looks like the first part of the stack trace has been omitted.

**Comment by samstarling** [comment]
@furahm01 Are you still having problems with this? If the dependency isn't found, you might need to [configure Maven to resolve from Bintray](https://bintray.com/docs/usermanual/formats/formats_mavenrepositories.html#anchorMavenResolve). I'm looking at ways to make this easier.

**Comment by samstarling** [comment]
@furahm01 Good news: the library is [now in Maven Central](http://search.maven.org/#artifactdetails%7Ccom.samstarling%7Cfinagle-prometheus_2.11%7C0.0.2%7Cjar).

**Comment by samstarling** [comment]
I'm going to close this due to lack of activity: please let me know if I can help with anything.
